Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,6 +25,18 @@ jobs:
             const tag = process.env.GITHUB_REF.split('/').pop();
             core.setOutput('version', tag.replace('v', ''));
 
+      - name: Get branch from TAG
+        id: get-branch
+        run: |
+          TAG=$(git describe --tags --exact-match 2>/dev/null)
+          if [ -z "$TAG" ]; then
+            echo "::error::No TAG found"
+            exit 1
+          fi
+          COMMIT_HASH=$(git rev-list -n 1 $TAG)
+          BRANCHES=$(git branch --contains $COMMIT_HASH)
+          echo "::set-output name=branches::$BRANCHES"
+
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Build Rust project in Docker
